export const FETCH_CANDIDATES_START = 'FETCH_CANDIDATES_START';
export const FETCH_CANDIDATES_SUCCESS = 'FETCH_CANDIDATES_SUCCESS';
export const FETCH_CANDIDATES_FAILED = 'FETCH_CANDIDATES_FAILED'

export const RENDER_TABLE_HEADER = 'RENDER_TABLE_HEADER'
export const RENDER_TABLE_DATA = 'RENDER_TABLE_DATA'
export const TOGGLE_TABLE = 'TOGGLE_TABLE'

export const CONSOLE_LOG = 'CONSOLE_LOG'

